### ISSUE TITLE
Static vs. dynamic `hasmethod`

### ISSUE THREAD

**Issue by tshort** [xiaodaigh/TraitWrappers.jl#2]
Your examples with `hasmethod` are dynamic, so they won't compile away. Consider mentioning that. 

Also consider pointing to [Tricks.jl](https://github.com/oxinabox/Tricks.jl/) by @oxinabox for a static version of `hasmethod` that should compile away.

**Comment by xiaodaigh** [comment]
Done.  Thanks for this.
